### PR TITLE
Reformat the create activity page, so it can handle multiple semesters

### PR DESCRIPTION
**Pull request by Christinarlong**
**Ticket:** https://github.com/orgs/sandboxnu/projects/9/views/1?pane=issue&itemId=22952790

**Frontend:**
Added checkboxes to activity submission page for semesters. Users can select multiple semesters to submit for their activity. And if Other is checked, users are required to enter a description for their activity submission.

**Backend:**
Modified Prisma schema for Activity to take in a description for the `other` checkbox.

**To run/test:**
Follow regular steps in README to manual test/see changes

**Images:**
**Form display:**
image

**With Other checked:**
image

### CODE REVIEW

**Review by maxpinheiro — APPROVED** [review]
Checkbox logic looks good! There are just a few style changes that we should make; they're unrelated to the checkbox, but there are some changes to this page in the [figma](https://www.figma.com/file/HOeEUn2qt2nP2EvklLLUHZ/Wireframes?node-id=2523-747&t=tkcJKmHOjYzXaA6t-0) that we should update before deploying this:
* input labels are too large: FormInput.tsx line 197, replace 'text-2xl' with 'text-base'
* too much spacing in input containers: FormInput.tsx line 199, replace 'space-y-3' with 'space-y-1'
* category header is too large, and should be bold. additionally we should add the text "New Activity" in front (see figma): FormInput.tsx line 205, replace `<p className="...">` with `<h2>New Activity - {categoryLabels[category]}</h2>`
* we need to make the form fill the entire page width so that the description input fills the entire page: FormContainer.tsx, add className `w-full` to both the `div`s

**Review by Suraj-Ram — APPROVED** [review]
Looks good! I agree with Max's points, especially the spacing.

**Comment by Christinarlong** [comment]
> Checkbox logic looks good! There are just a few style changes that we should make; they're unrelated to the checkbox, but there are some changes to this page in the [figma](https://www.figma.com/file/HOeEUn2qt2nP2EvklLLUHZ/Wireframes?node-id=2523-747&t=tkcJKmHOjYzXaA6t-0) that we should update before deploying this:
> 
>     * input labels are too large: FormInput.tsx line 197, replace 'text-2xl' with 'text-base'
> 
>     * too much spacing in input containers: FormInput.tsx line 199, replace 'space-y-3' with 'space-y-1'
> 
>     * category header is too large, and should be bold. additionally we should add the text "New Activity" in front (see figma): FormInput.tsx line 205, replace `<p className="...">` with `<h2>New Activity - {categoryLabels[category]}</h2>`
> 
>     * we need to make the form fill the entire page width so that the description input fills the entire page: FormContainer.tsx, add className `w-full` to both the `div`s

image

**Review by maxpinheiro — APPROVED** [review]
LGTM 👍

**Comment by Christinarlong** [comment]
> LGTM 👍

poggers

**Pull request merged**
